### ISSUE TITLE
Sizes of tensors must match except in dimension 0

### ISSUE THREAD

**Issue by douxWh** [facebookresearch/noisy_few_shot#4]
Dear @kevinjliang ,
when I run the command ,bash scripts/train_transf.sh

Traceback (most recent call last):
  File "D:\PostGraduate\code\FSL\noisy_few_shot-main\noisy_few_shot-main\main.py", line 509, in <module>
    train_losses, train_accs = meta_trainer.loss_acc(
  File "D:\PostGraduate\code\FSL\noisy_few_shot-main\noisy_few_shot-main\few_shot_utils.py", line 231, in loss_acc
    outputs = self.model(data, mask_indices["support"])
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PostGraduate\code\FSL\noisy_few_shot-main\noisy_few_shot-main\models.py", line 265, in forward
    transformer_output = self.transformer(transformer_input).squeeze(
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PostGraduate\code\FSL\noisy_few_shot-main\noisy_few_shot-main\models.py", line 113, in forward
    cls_sup_embeds = torch.cat((cls_tokens, x), dim=0)  # (ways*(shot+1), dim)   x-->（25,1600)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 128 but got size 1600 for tensor number 1 in the list.

Process finished with exit code 1

It will run successfully only when the parameter, trans-d-model,is set to 1600.

**Comment by kevinjliang** [comment]
Hm, I am unable to reproduce this error. Did you change any other args in `train_transf.sh`? It should run as is, as long as you've run `train_backbone.sh` to train the feature extractor first.
